### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by Baayeh** [Strangeal/ClinixGo#16]
## Creation of Kanban Board

- [Link to Project](https://github.com/users/Strangeal/projects/3)
- We are 4 in the group:
   -  @Baayeh 
   - @Paul-js-hub 
   - @NahnahAJ
   - @Strangeal 

### Kanban Board Screenshot
![image](https://user-images.githubusercontent.com/20049193/220385323-6515c1e1-0fc1-454c-af09-45e3ab48e94c.png)

**Comment by Meltrust** [comment]
Hi @Baayeh,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All tasks have been pointed✔️ 
- Pointings are equal enough✔️ 
- All tasks have descriptions✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
